services:
  backend_inicial:
    #build:
    #  context: ./backend_inicial
    #  dockerfile: Dockerfile
    image: rluisangulo/checker_completo-backend_inicial
    container_name: backend_inicial
    ports:
      - 3000:3000
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  service_monitor:
    #build:
    #  context: ./service_monitor
    #  dockerfile: Dockerfile
    image: rluisangulo1972/checker_completo-service_monitor
    container_name: service_monitor
    environment: # indicamos los valores que tendrán las variables de entorno 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BACKEND_INICIAL_NAME: backend_inicial
      BACKEND_INICIAL_HOST: backend_inicial
      BACKEND_INICIAL_PORT: 3000
    ports:
      - 4000:4000
    depends_on:
      - redis
      - backend_inicial
  web_nginx:
    #build:
    #  context: ./web_detalle
    #  dockerfile: Dockerfile
    image: rluisangulo1972/checker_completo-web_nginx
    container_name: nginx_web
    volumes:
      - ./web_detalle/index.html:/usr/share/nginx/html/index.html
    ports:
      - 8080:80
    